name: first-workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome note
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
  build:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: welcome note
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
      - name: npm build
        run: npm run build
        
        
         
