name: first-workflow
on: 
  push: 
    branches: ['master']
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome note
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout code
        uses: actions/checkout@v3
      - run: cd "02 Starting Project"
      - name: download node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      - run: npm clean
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm test
        
        
         
