name: first-workflow
on: 
  push: 
    branches: ['master']
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: welcome note
        run: echo "${{ toJSON(github.event) }}"
      - name: checkout code
        uses: actions/checkout@v3

      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm test
        
        
         
